---
abstract: 'Convert POD to README file'
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Readme
provides:
  Pod::Readme:
    file: lib/Pod/Readme.pm
    version: 0.10
recommends:
  Test::Pod: 1.00
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
requires:
  Carp: 0
  File::Copy: 0
  IO::File: 0
  Pod::Text: 3.0
  Regexp::Common: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
