---
abstract: 'Generate a README file from POD'
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  Exporter::Lite: 0
  ExtUtils::MakeMaker: 6.59
  File::Compare: 0
  File::Temp: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::Kit: 2.10
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Readme
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Pod::Man: 0
  Pod::Markdown: 0
  Pod::Simple::LaTeX: 0
  Type::Tiny::XS: 0
requires:
  CPAN::Changes: 0.30
  CPAN::Meta: 0
  Carp: 0
  Class::Method::Modifiers: 0
  Exporter::Lite: 0
  ExtUtils::MakeMaker: 6.56
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  Hash::Util: 0
  IO: 0
  Module::CoreList: 0
  Module::Load: 0
  Moo: 0
  Moo::Role: 0
  MooX::HandlesVia: 0
  Path::Class: 0.33
  Pod::Simple: 0
  Scalar::Util: 0
  Try::Tiny: 0
  Type::Tiny: 0
  Types::Standard: 0
  namespace::autoclean: 0
  perl: 5.10.1
  version: 0.77
resources:
  bugtracker: https://github.com/bigpresh/Pod-Readme/issues
  homepage: https://metacpan.org/pod/Pod::Readme
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/bigpresh/Pod-Readme.git
version: 1.000001_002
